name:  MUX.Loaders
author:  lavmax
current:  1.1
category:  Interface
tags:  [loader,ajax,animation]
demo:  http://lavmax.github.com/MUX.Loaders
docs:  https://github.com/lavmax/MUX.Loaders/blob/master/Docs/MUX.Loaders.md